name: noip
base: core18
version: 2.1.9
summary: No-IP Dynamic DNS Update Client for Linux
description: |
  Keep your current IP address in sync with your No-IP host or domain
  with No-IP's Dynamic Update Client (DUC).
  (Unoffical)

apps:
  noip-client:
    command: bin/noip2
    plugs: [network]
  configure:
    command: configure
    plugs: [network]
  launcher:
    daemon: simple
    command: launcher
    plugs: [network]

grade: devel
confinement: devmode

architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64
parts:
  client:
#    make-parameters: ["-C","noip-2.1.9-1"]
#    make-install-var: PREFIX
    source: src
    plugin: make
  noipcode:
    source: http://www.noip.com/client/linux/noip-duc-linux.tar.gz
    plugin: dump
    source-type: tar
    organize:
        noip-duc-linux.tar.gz: src/noip-duc-linux.tar.gz
